### ISSUE TITLE
Transfer repo to me?

### ISSUE THREAD

**Issue by adrn** [adrn/mpipool#4]
Yo -- you want to transfer this over to me since, as you said, you don't use it much anymore?

**Comment by dfm** [comment]
Apparently I can't transfer it because you already have a fork. How about we redirect users to your fork in the README?

**Comment by adrn** [comment]
That's fine by me, but it would be easy to delete the fork on github and just update the remotes locally...

**Comment by dfm** [comment]
Let's just do that then.

**Comment by adrn** [comment]
Boom, done

**Comment by adrn** [comment]
Donezo
